/**
 * File Processor Utility
 * Handles sanitization, normalization, and formatting of AI-generated files.
 */

import * as path from 'path';
import { WorkerPool } from './worker-pool';
import { createLogger } from '../logger';

const logger = createLogger('file-processor');

/**
 * Curated version map for packages commonly generated by AI.
 * Used to replace "latest", "", or "*" with known-good pinned versions
 * that Sandpack can reliably resolve.
 */
const PINNED_VERSIONS: Record<string, string> = {
    // React core
    'react': '^18.2.0',
    'react-dom': '^18.2.0',
    'react-router-dom': '^6.22.0',
    '@types/react': '^18.2.0',
    '@types/react-dom': '^18.2.0',

    // Icons & UI
    'lucide-react': '^0.344.0',
    'react-icons': '^5.0.1',
    '@heroicons/react': '^2.1.1',
    '@radix-ui/react-dialog': '^1.0.5',
    '@radix-ui/react-dropdown-menu': '^2.0.6',
    '@radix-ui/react-select': '^2.0.0',
    '@radix-ui/react-tooltip': '^1.0.7',
    '@radix-ui/react-tabs': '^1.0.4',
    '@radix-ui/react-switch': '^1.0.3',
    '@radix-ui/react-checkbox': '^1.0.4',
    '@radix-ui/react-slider': '^1.1.2',

    // State management
    'zustand': '^4.5.2',
    'jotai': '^2.7.0',
    'valtio': '^1.13.0',
    'immer': '^10.0.3',
    '@tanstack/react-query': '^5.29.0',

    // Forms & validation
    'react-hook-form': '^7.51.0',
    'zod': '^3.22.4',
    'yup': '^1.4.0',

    // Animation
    'framer-motion': '^11.0.8',
    'react-spring': '^9.7.3',
    'react-transition-group': '^4.4.5',

    // Charts & visualization
    'recharts': '^2.12.2',
    'chart.js': '^4.4.2',
    'react-chartjs-2': '^5.2.0',
    'd3': '^7.9.0',

    // Utilities
    'axios': '^1.6.8',
    'clsx': '^2.1.0',
    'classnames': '^2.5.1',
    'date-fns': '^3.6.0',
    'dayjs': '^1.11.10',
    'moment': '^2.30.1',
    'lodash': '^4.17.21',
    '@types/lodash': '^4.17.0',
    'uuid': '^9.0.1',
    '@types/uuid': '^9.0.8',

    // Markdown & syntax highlighting
    'react-markdown': '^9.0.1',
    'marked': '^12.0.0',
    'react-syntax-highlighter': '^15.5.0',
    'highlight.js': '^11.9.0',

    // Drag and drop
    'react-beautiful-dnd': '^13.1.1',
    '@dnd-kit/core': '^6.1.0',
    '@dnd-kit/sortable': '^8.0.0',

    // Date pickers & selects
    'react-datepicker': '^6.6.0',
    'react-select': '^5.8.0',

    // MUI
    '@mui/material': '^5.15.10',
    '@mui/icons-material': '^5.15.10',
    '@emotion/react': '^11.11.4',
    '@emotion/styled': '^11.11.0',

    // Styled components
    'styled-components': '^6.1.8',

    // TypeScript
    'typescript': '^5.4.3',
};

/** Version strings that should be replaced with pinned versions. */
const BAD_VERSIONS = new Set(['latest', '', '*', 'next', 'canary', 'beta', 'alpha']);

/**
 * Post-process a package.json content to pin "latest"/empty versions
 * using the curated version map. Unknown packages with bad versions are left as-is.
 */
function pinPackageVersions(content: string): string {
    let pkg: Record<string, unknown>;
    try {
        pkg = JSON.parse(content);
    } catch {
        return content; // Not valid JSON — leave for Prettier to catch
    }

    let changed = false;
    const depFields = ['dependencies', 'devDependencies', 'peerDependencies'] as const;

    for (const field of depFields) {
        const deps = pkg[field];
        if (!deps || typeof deps !== 'object') continue;

        for (const [name, version] of Object.entries(deps as Record<string, string>)) {
            if (BAD_VERSIONS.has(version) && PINNED_VERSIONS[name]) {
                (deps as Record<string, string>)[name] = PINNED_VERSIONS[name];
                changed = true;
                logger.debug('Pinned package version', { name, from: version, to: PINNED_VERSIONS[name] });
            }
        }
    }

    return changed ? JSON.stringify(pkg, null, 2) : content;
}

// Lazy initialization of worker pool
let workerPool: WorkerPool | null = null;

function getWorkerPool(): WorkerPool {
    if (!workerPool) {
        // In Next.js, __dirname can be unpredictable when bundled.
        // We use process.cwd() to resolve from the project root instead.
        const workerScript = path.resolve(process.cwd(), 'lib/workers/prettier-worker.js');
        workerPool = new WorkerPool(workerScript);
    }
    return workerPool;
}

export interface ProcessedFile {
    path: string;
    content: string;
    warning?: { message: string; type: 'formatting' };
}

export interface FileProcessorOptions {
    addFrontendPrefix?: boolean;
}

/**
 * Fix literal newlines inside string literals.
 * The AI sometimes generates code like: split('\n') where \n is a literal newline
 * This fixes it to: split('\\n')
 */
function fixLiteralNewlinesInStrings(content: string): string {
    // Only target specific safe patterns where a string contains JUST a newline
    // This repairs split('\n') -> quote, newline, quote
    // We avoid matching across lines by ensuring there's no other content
    const singleQuotePattern = /'\n'/g;
    const doubleQuotePattern = /"\n"/g;

    let fixed = content;

    // Fix single-quoted strings (convert to escaped)
    fixed = fixed.replace(singleQuotePattern, "'\\n'");

    // Fix double-quoted strings
    fixed = fixed.replace(doubleQuotePattern, '"\\n"');

    // Also handle CRLF
    fixed = fixed.replace(/'\r\n'/g, "'\\r\\n'");
    fixed = fixed.replace(/"\r\n"/g, '"\\r\\n"');

    return fixed;
}

/**
 * Fix common JSON syntax errors from AI output:
 *  - Double commas: `true,   ,   "next"` → `true,   "next"`
 *  - Trailing commas before } or ]: `"x": 1,\n}` → `"x": 1\n}`
 */
function fixJsonSyntax(content: string): string {
    // Remove duplicate consecutive commas (with optional whitespace between them)
    let fixed = content.replace(/,(\s*),+/g, ',$1');
    // Remove trailing commas before closing brace or bracket
    fixed = fixed.replace(/,(\s*[}\]])/g, '$1');
    return fixed;
}

/**
 * Process a single file: sanitize path, normalize newlines, format with Prettier
 */
export async function processFile(
    path: string,
    content: string,
    options: FileProcessorOptions = {}
): Promise<ProcessedFile> {
    // Sanitize path: remove accidental spaces
    let sanitizedPath = path.replace(/\s+/g, '');

    // Add frontend/ prefix if needed
    if (options.addFrontendPrefix && !sanitizedPath.startsWith('frontend/')) {
        sanitizedPath = `frontend/${sanitizedPath}`;
    }

    // STEP 1: Normalize global newlines (restore structural newlines)
    // AI often returns \n tokens that should be real newlines
    let normalizedContent = content;
    if (normalizedContent.includes('\\n')) {
        normalizedContent = normalizedContent.replace(/\\n/g, '\n');
    }
    if (normalizedContent.includes('\\t')) {
        normalizedContent = normalizedContent.replace(/\\t/g, '\t');
    }

    // STEP 2: Fix any newlines that ended up inside string literals
    // This handles cases where \n was meant to be an escape sequence inside a string
    normalizedContent = fixLiteralNewlinesInStrings(normalizedContent);

    // STEP 2b: Pin package.json versions (replace "latest"/empty with curated versions)
    if (sanitizedPath.endsWith('package.json')) {
        normalizedContent = pinPackageVersions(normalizedContent);
    }

    // STEP 2c: Sanitize any .json file content — fix double commas and trailing commas
    // AI frequently generates "key": value,   ,   "next" or trailing commas before } / ]
    if (sanitizedPath.endsWith('.json')) {
        normalizedContent = fixJsonSyntax(normalizedContent);
    }

    // STEP 3: Handle double-escaped sequences from JSON
    if (normalizedContent.includes('\\\\n')) {
        normalizedContent = normalizedContent.replace(/\\\\n/g, '\\n');
    }
    if (normalizedContent.includes('\\\\t')) {
        normalizedContent = normalizedContent.replace(/\\\\t/g, '\\t');
    }

    // Format with Prettier (via Worker Pool)
    let formattingWarning: { message: string; type: 'formatting' } | undefined;
    try {
        const pool = getWorkerPool();
        const formatted = await pool.runTask({ content: normalizedContent, filePath: path });

        if (formatted !== normalizedContent) {
            logger.debug('File formatted successfully (worker)', { path });
            normalizedContent = formatted;
        }
    } catch (e) {
        const errorMsg = e instanceof Error ? e.message : 'Unknown error';
        logger.error('Failed to format file', {
            path,
            error: errorMsg
        });
        // On error, we keep normalizedContent as is (graceful degradation)
        formattingWarning = {
            message: `Failed to format with Prettier: ${errorMsg}. Using original content.`,
            type: 'formatting'
        };
    }

    return {
        path: sanitizedPath,
        content: normalizedContent,
        warning: formattingWarning
    };
}

export interface ProcessFilesResult {
    files: Record<string, string>;
    warnings: Array<{ path: string; message: string; type: 'formatting' }>;
}

/**
 * Process multiple files in parallel for better performance.
 * Returns both processed files and any warnings encountered.
 */
export async function processFiles(
    files: Array<{ path: string; content: string }>,
    options: FileProcessorOptions = {}
): Promise<ProcessFilesResult> {
    const validFiles = files.filter(f => f.path && f.content);

    const processed = await Promise.all(
        validFiles.map(file => processFile(file.path, file.content, options))
    );

    const result: Record<string, string> = {};
    const warnings: Array<{ path: string; message: string; type: 'formatting' }> = [];

    for (const { path, content, warning } of processed) {
        result[path] = content;
        if (warning) {
            warnings.push({ path, ...warning });
        }
    }

    return { files: result, warnings };
}
